apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.fullname" . }}-configure-common
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
data:

  template-common.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">
        {{- if .Values.configmap.extraConfig }}
{{ toYaml .Values.configmap.extraConfig | indent 8 }}
        {{- end }}

        <cluster-user>exampleUser</cluster-user>
        <cluster-password>secret</cluster-password>

        {{- $name := default .Chart.Name .Values.nameOverride -}}
        {{- $fullname := include "artemis.fullname" . -}}
        {{- $releaseName := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
        {{- $releaseNamespace := .Release.Namespace -}}

        <connectors>
          {{ range $i,$t := until (int .Values.masterReplicas) }}
          <connector name="{{ $fullname }}-master-{{ $i }}">tcp://{{ $fullname }}-master-{{ $i }}.{{ $releaseName }}-master.{{ $releaseNamespace }}.svc.cluster.local:61616</connector>
          {{end}}
          {{ range $i,$t := until (int .Values.slaveReplicas) }}
          <connector name="{{ $fullname }}-slave-{{ $i }}">tcp://{{ $fullname }}-slave-{{ $i }}.{{ $releaseName }}-slave.{{ $releaseNamespace }}.svc.cluster.local:61616</connector>
          {{end}}

        </connectors>


        <cluster-connections>
          <cluster-connection name="{{ $releaseName }}">
            <connector-ref>netty-connector</connector-ref>
            <retry-interval>500</retry-interval>
            <retry-interval-multiplier>1.1</retry-interval-multiplier>
            <max-retry-interval>5000</max-retry-interval>
            <initial-connect-attempts>-1</initial-connect-attempts>
            <reconnect-attempts>-1</reconnect-attempts>

            <message-load-balancing>ON_DEMAND</message-load-balancing>
            <max-hops>1</max-hops>

            <static-connectors>
            {{ range $i,$t := until (int .Values.masterReplicas) }}
                <connector-ref>{{ $fullname }}-master-{{ $i }}</connector-ref>
            {{ end }}
            {{ range $i,$t := until (int .Values.slaveReplicas) }}
                <connector-ref>{{ $fullname }}-slave-{{ $i }}</connector-ref>
            {{ end }}
            </static-connectors>

         </cluster-connection>
       </cluster-connections>
      </core>
    </configuration>

